#!/bin/sh
i=enp1s0 ; me=$0 ; user=root ;
#dongle fe80::c2a0:bbff:fe58:b292 d1312 ddong
#dongle fe80::a6d:41ff:fee6:2681 apple adong
#dongle fe80::2ad:24ff:fe3e:61be extra
#dongle fe80::2ad:24ff:fe3e:61c0 peio
#dongle fe80::2ad:24ff:fe3e:61c1 joxean
get_ll(){ ll=$(grep \#don $me|grep -v grep|grep $1|cut -d\  -f2|head -n1)%$i; }
case "$1" in 
  all) shift; grep \#don $me|grep -v grep|cut -d\  -f3|tr '\n' ' ';echo ;;
  list) shift; grep \#don $me|grep -v grep ;;
  target) shift; get_ll $1; echo \[$ll\] ;;
  scp) shift; get_ll $1; ping6 -c2 $ll && scp -6 $2 $user@\[$ll\]: ;;
  ssh) shift; get_ll $1; shift; ping6 -c2 $ll && ssh -6 $user@$ll $@ ;;
  *) get_ll $1; shift; ping6 -c2 $ll && ssh -6 $user@$ll $@ ;;
esac
